""""""""""""""""""""""""""""""""""""""""""""""""
" => Pathogen 
""""""""""""""""""""""""""""""""""""""""""""""""
execute pathogen#infect()

""""""""""""""""""""""""""""""""""""""""""""""""
" => General
""""""""""""""""""""""""""""""""""""""""""""""""
syntax on
filetype plugin indent on
set nocompatible
set sessionoptions-=options


" Set map leader
let mapleader = ","

" Fast saving
nmap <leader>w :w!<cr>
nmap <leader>r :w!<cr>:q<cr>
" Edit vimrc
nnoremap<leader>ev :split $MYVIMRC<cr>
" Source vimrc
nnoremap<leader>sv :source $MYVIMRC<cr>
" Close current buffer
map <leader>ba :Bclose<cr>
" Close all the buffers
map <leader>ba :1,100 bd!<cr>

""""""""""""""""""""""""""""""""""""""""""""""""
" => Nvim-R Shortcuts 
""""""""""""""""""""""""""""""""""""""""""""""""
" Spacebar sends current line or current selection
vmap <Space> <Plug>RDSendSelection
nmap <Space> <Plug>RDSendLine


""""""""""""""""""""""""""""""""""""""""""""""""
" => VIM User Interface
""""""""""""""""""""""""""""""""""""""""""""""""
" Map key sequence j-k to the escape button
"inoremap jk <Esc>

"let g:easyescape_chars = { "j": 1, "k": 1}
let g:easyescape_chars = { "j": 1, "k": 1, "z": 1, "9": 1}
let g:easyescape_timeout = 100
cnoremap jk <ESC>
cnoremap kj <ESC>
inoremap jk <ESC>
inoremap kj <ESC>
"imap jk <Esc> 

set ruler
set cmdheight=2
set backspace=indent,eol,start
set whichwrap+=<,>,h,l
set hlsearch
"set paste
set laststatus=2
set pastetoggle=99
set wrap

set tabstop=4 softtabstop=0 shiftwidth=4 smarttab
"set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
set ai
set si
set linespace=2
set foldmethod=marker
"-----------------------------------------------
" zz to toggle highlight.
let hlstate=0
nnoremap zz :if (hlstate%2 == 0) \| nohlsearch \| else \| set hlsearch \| endif \| let hlstate=hlstate+1<cr>

"""""""""""""""""""""""""""""""""""""""""""""""
" => Creating line folds 
"""""""""""""""""""""""""""""""""""""""""""""""
" Folds are set by visible text markers rather than invisible manual marks
"set foldmethod=marker

" save and restore folds when a file is closed and re-opened
au BufWinLeave * mkview
au BufWinEnter * silent loadview

"""""""""""""""""""""""""""""""""""""""""""""""
" => Moving Around Windows 
"""""""""""""""""""""""""""""""""""""""""""""""
" Smart way to nove between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

"""""""""""""""""""""""""""""""""""""""""""""""
" => Color and Fonts
"""""""""""""""""""""""""""""""""""""""""""""""
" Faves
"colorscheme woju
"colorscheme znake
"colorscheme yuejiu
"colorscheme xterm16
"colorscheme xemacs
"colorscheme wood
"colorscheme vimbrant
"colorscheme wellsokai
"colorscheme wasabi256
"colorscheme vorange
"colorscheme vimbrains
"colorscheme valloric



syntax enable
"set background=dark
"let g:alduin_Shout_Dragon_Aspect = 1
"colorscheme alduin 
"let g:airline_theme='afterglow'
"colorscheme afterglow
"let g:challenger_deep_termcolors
"colorscheme challenger_deep
let g:jellybeans_use_lowcolor_black = 1
colorscheme jellybeans
"let g:airline_theme='minimalist'
"let g:airline_powerline_fonts = 1
"let g:airline#extensions#tabline#enabled = 1
"colorscheme minimalist
"let g:molokai_original = 1
"colorscheme molokai
"let g:airline_theme = 'tender'
"colorscheme tender
"colorscheme abyss
"colorscheme advantage
"colorscheme adventurous
"colorscheme afterglow
"colorscheme antares
"colorscheme bitterjug
"colorscheme bluez
"colorscheme 0x7A69_dark
"colorscheme 1989
"colorscheme 256-grayvim
"colorscheme 256-jungle
"colorscheme 256_noir
"colorscheme 3dglasses
"colorscheme abbott
"colorscheme abra
"colorscheme abyss
"colorscheme adam
"colorscheme adaryn
"colorscheme adobe
"colorscheme adrian
"colorscheme advantage
"colorscheme adventurous
"colorscheme afterglow
"colorscheme af
"colorscheme aiseered
"colorscheme alduin
"colorscheme ancient
"colorscheme anderson
"colorscheme angr
"colorscheme anotherdark
"colorscheme ansi_blows
"colorscheme antares
"colorscheme apprentice
"colorscheme aquamarine
"colorscheme aqua
"colorscheme arcadia
"colorscheme archery
"colorscheme argonaut
"colorscheme ashen
"colorscheme asmanian2
"colorscheme asmanian_blood
"colorscheme asmdev2
"colorscheme asmdev
"colorscheme astronaut
"colorscheme asu1dark
"colorscheme Atelier_CaveDark
"colorscheme Atelier_CaveLight
"colorscheme Atelier_DuneDark
"colorscheme Atelier_DuneLight
"colorscheme Atelier_EstuaryDark
"colorscheme Atelier_EstuaryLight
"colorscheme Atelier_ForestDark
"colorscheme Atelier_ForestLight
"colorscheme Atelier_HeathDark
"colorscheme Atelier_HeathLight
"colorscheme Atelier_LakesideDark
"colorscheme Atelier_LakesideLight
"colorscheme Atelier_PlateauDark
"colorscheme Atelier_PlateauLight
"colorscheme Atelier_SavannaDark
"colorscheme Atelier_SavannaLight
"colorscheme Atelier_SeasideDark
"colorscheme Atelier_SeasideLight
"colorscheme Atelier_SulphurpoolDark
"colorscheme Atelier_SulphurpoolLight
"colorscheme atom
"colorscheme aurora
"colorscheme automation
"colorscheme autumnleaf
"colorscheme autumn
"colorscheme ayu
"colorscheme babymate256
"colorscheme badwolf
"colorscheme bandit
"colorscheme base16-ateliercave
"colorscheme base16-atelierdune
"colorscheme base16-atelierestuary
"colorscheme base16-atelierforest
"colorscheme base16-atelierheath
"colorscheme base16-atelierlakeside
"colorscheme base16-atelierplateau
"colorscheme base16-ateliersavanna
"colorscheme base16-atelierseaside
"colorscheme base16-ateliersulphurpool
"colorscheme base16-railscasts
"colorscheme base
"colorscheme basic-dark
"colorscheme basic-light
"colorscheme basic
"colorscheme baycomb
"colorscheme bayQua
"colorscheme bclear
"colorscheme beachcomber
"colorscheme beauty256
"colorscheme beekai
"colorscheme behelit
"colorscheme benlight
"colorscheme Benokai
"colorscheme bensday
"colorscheme billw
"colorscheme biogoo
"colorscheme birds-of-paradise
"colorscheme bitterjug
"colorscheme black_angus
"colorscheme blackbeauty
"colorscheme blackboard
"colorscheme blackdust
"colorscheme blacklight
"colorscheme BlackSea
"colorscheme Black
"colorscheme blaquemagick
"colorscheme blazer
"colorscheme blink
"colorscheme Blue2
"colorscheme bluechia
"colorscheme bluedrake
"colorscheme bluegreen
"colorscheme bluenes
"colorscheme blueprint
"colorscheme blueshift
"colorscheme blues
"colorscheme blue
"colorscheme bluez
"colorscheme blugrine
"colorscheme bluish
"colorscheme bmichaelsen
"colorscheme boa
"colorscheme bocau
"colorscheme bog
"colorscheme boltzmann
"colorscheme borland
"colorscheme breeze
"colorscheme breezy
"colorscheme brighton
"colorscheme briofita
"colorscheme broduo
"colorscheme brogrammer
"colorscheme brookstream
"colorscheme brown
"colorscheme bubblegum-256-dark
"colorscheme bubblegum-256-light
"colorscheme bubblegum
"colorscheme buddy
"colorscheme burnttoast256
"colorscheme busierbee
"colorscheme busybee
"colorscheme buttercream
"colorscheme bvemu
"colorscheme bw
"colorscheme c16gui
"colorscheme C64
"colorscheme cabin
"colorscheme cake16
"colorscheme cake
"colorscheme calmar256-dark
"colorscheme calmar256-light
"colorscheme camo
"colorscheme campfire
"colorscheme candycode
"colorscheme candyman
"colorscheme CandyPaper
"colorscheme candy
"colorscheme caramel
"colorscheme carrot
"colorscheme carvedwoodcool
"colorscheme carvedwood
"colorscheme cascadia
"colorscheme celtics_away
"colorscheme cgpro
"colorscheme chalkboard
"colorscheme chance-of-storm
"colorscheme charged-256
"colorscheme charon
"colorscheme Chasing_Logic
"colorscheme chela_light
"colorscheme cherryblossom
"colorscheme chlordane
"colorscheme ChocolateLiquor
"colorscheme ChocolatePapaya
"colorscheme chocolate
"colorscheme chroma
"colorscheme chrysoprase
"colorscheme clarity
"colorscheme cleanphp
"colorscheme cleanroom
"colorscheme clearance
"colorscheme cloudy
"colorscheme clue
"colorscheme cobalt2
"colorscheme cobaltish
"colorscheme cobalt
"colorscheme coda
"colorscheme codeblocks_dark
"colorscheme codeburn
"colorscheme codedark
"colorscheme CodeFactoryv3
"colorscheme codeschool
"colorscheme coffee
"colorscheme coldgreen
"colorscheme colorer
"colorscheme colorful256
"colorscheme colorful
"colorscheme colorsbox-faff
"colorscheme colorsbox-greenish
"colorscheme colorsbox-material
"colorscheme colorsbox-stblue
"colorscheme colorsbox-stbright
"colorscheme colorsbox-steighties
"colorscheme colorsbox-stnight
"colorscheme colorzone
"colorscheme contrastneed
"colorscheme contrasty
"colorscheme cool
"colorscheme corn
"colorscheme corporation
"colorscheme crayon
"colorscheme crt
"colorscheme crunchbang
"colorscheme cthulhian
"colorscheme custom
"colorscheme c
"colorscheme cyberpunk
"colorscheme d8g_01
"colorscheme d8g_02
"colorscheme d8g_03
"colorscheme d8g_04
"colorscheme dante
"colorscheme Dark2
"colorscheme darkblack
"colorscheme darkblue2
"colorscheme darkblue
"colorscheme darkBlue
"colorscheme darkbone
"colorscheme darkburn
"colorscheme DarkDefault
"colorscheme darkdevel
"colorscheme darkdot
"colorscheme darkeclipse
"colorscheme darkerdesert
"colorscheme darker-robin
"colorscheme darkglass
"colorscheme darkocean
"colorscheme darkrobot
"colorscheme dark-ruby
"colorscheme darkslategray
"colorscheme darkspectrum
"colorscheme darktango
"colorscheme Dark
"colorscheme darkzen
"colorscheme darkZ
"colorscheme darth
"colorscheme dawn
"colorscheme deepsea
"colorscheme deep-space
"colorscheme default
"colorscheme delek
"colorscheme delphi
"colorscheme denim
"colorscheme derefined
"colorscheme desert256v2
"colorscheme desert256
"colorscheme desertedoceanburnt
"colorscheme desertedocean
"colorscheme desertEx
"colorscheme desertink
"colorscheme desert
"colorscheme despacio
"colorscheme detailed
"colorscheme deus
"colorscheme devbox-dark-256
"colorscheme DevC++
"colorscheme Dev_Delight
"colorscheme deveiate
"colorscheme developer
"colorscheme Dim2
"colorscheme DimBlue
"colorscheme DimGreens
"colorscheme DimGreen
"colorscheme DimGrey
"colorscheme DimRed
"colorscheme DimSlate
"colorscheme Dim
"colorscheme diokai
"colorscheme disciple
"colorscheme distill
"colorscheme distinguished
"colorscheme django
"colorscheme donbass
"colorscheme donttouchme
"colorscheme doorhinge
"colorscheme doriath
"colorscheme dracula
"colorscheme dual
"colorscheme dull
"colorscheme duotone-darkcave
"colorscheme duotone-darkdesert
"colorscheme duotone-darkearth
"colorscheme duotone-darkforest
"colorscheme duotone-darkheath
"colorscheme duotone-darklake
"colorscheme duotone-darkmeadow
"colorscheme duotone-darkpark
"colorscheme duotone-darkpool
"colorscheme duotone-darksea
"colorscheme duotone-darkspace
"colorscheme duotone-dark
"colorscheme dusk
"colorscheme dw_blue
"colorscheme dw_cyan
"colorscheme dw_green
"colorscheme dw_orange
"colorscheme dw_purple
"colorscheme dw_red
"colorscheme dw_yellow
"colorscheme dzo
"colorscheme earendel
"colorscheme earthburn
"colorscheme earth
"colorscheme eclipse
"colorscheme eclm_wombat
"colorscheme ecostation
"colorscheme editplus
"colorscheme edo_sea
"colorscheme ego
"colorscheme eink
"colorscheme ekinivim
"colorscheme ekvoli
"colorscheme eldar
"colorscheme elda
"colorscheme elflord
"colorscheme elise
"colorscheme elisex
"colorscheme elrodeo
"colorscheme elrond
"colorscheme emacs
"colorscheme enigma
"colorscheme enzyme
"colorscheme erez
"colorscheme eva01-LCL
"colorscheme eva01
"colorscheme eva
"colorscheme evening1
"colorscheme evening
"colorscheme evokai
"colorscheme evolution
"colorscheme fahrenheit
"colorscheme fairyfloss
"colorscheme falcon
"colorscheme far
"colorscheme felipec
"colorscheme feral
"colorscheme fight-in-the-shade
"colorscheme fine_blue
"colorscheme firewatch
"colorscheme flatcolor
"colorscheme flatlandia
"colorscheme flatland
"colorscheme flattened_dark
"colorscheme flattened_light
"colorscheme flattown
"colorscheme flattr
"colorscheme flatui
"colorscheme fnaqevan
"colorscheme fog
"colorscheme fokus
"colorscheme forneus
"colorscheme freya
"colorscheme frood
"colorscheme frozen
"colorscheme fruidle
"colorscheme fruit
"colorscheme fruity
"colorscheme fu
"colorscheme fx
"colorscheme gardener
"colorscheme garden
"colorscheme gemcolors
"colorscheme genericdc-light
"colorscheme genericdc
"colorscheme gentooish
"colorscheme getafe
"colorscheme getfresh
"colorscheme ghostbuster
"colorscheme github
"colorscheme gobo
"colorscheme golded
"colorscheme goldenrod
"colorscheme golden
"colorscheme goodwolf
"colorscheme google
"colorscheme gor
"colorscheme gotham256
"colorscheme gotham
"colorscheme gothic
"colorscheme grape
"colorscheme gravity
"colorscheme grayorange
"colorscheme graywh
"colorscheme grb256
"colorscheme greens
"colorscheme Green
"colorscheme greenvision
"colorscheme greenwint
"colorscheme grey2
"colorscheme greyblue
"colorscheme greygull
"colorscheme grishin
"colorscheme gruvbox
"colorscheme gryffin
"colorscheme guardian
"colorscheme guepardo
"colorscheme h80
"colorscheme habiLight
"colorscheme happy_hacking
"colorscheme harlequin
"colorscheme heliotrope
"colorscheme hemisu
"colorscheme herald
"colorscheme herokudoc-gvim
"colorscheme herokudoc
"colorscheme heroku-terminal
"colorscheme heroku
"colorscheme hhazure
"colorscheme hhdblue
"colorscheme hhdcyan
"colorscheme hhdgray
"colorscheme hhdgreen
"colorscheme hhdmagenta
"colorscheme hhdred
"colorscheme hhdyellow
"colorscheme hhorange
"colorscheme hhpink
"colorscheme hhspring
"colorscheme hhteal
"colorscheme hhviolet
"colorscheme highlighter_term_bright
"colorscheme highlighter_term
"colorscheme highwayman
"colorscheme hilal
"colorscheme holokai
"colorscheme hornet
"colorscheme horseradish256
"colorscheme hotpot
"colorscheme hybrid-light
"colorscheme hybrid_material
"colorscheme hybrid_reverse
"colorscheme hybrid
"colorscheme hydrangea
"colorscheme iangenzo
"colorscheme ibmedit
"colorscheme icansee
"colorscheme iceberg
"colorscheme immortals
"colorscheme impactG
"colorscheme impactjs
"colorscheme impact
"colorscheme industrial
"colorscheme industry
"colorscheme ingretu
"colorscheme inkpot
"colorscheme inori
"colorscheme ir_black
"colorscheme ironman
"colorscheme itg_flat_transparent
"colorscheme itg_flat
"colorscheme itsasoa
"colorscheme jaime
"colorscheme jammy
"colorscheme janah
"colorscheme japanesque
"colorscheme jelleybeans
"colorscheme jellybeans
"colorscheme jellygrass
"colorscheme jellyx
"colorscheme jhdark
"colorscheme jhlight
"colorscheme jiks
"colorscheme jitterbug
"colorscheme kalahari
"colorscheme kalisi
"colorscheme kaltex
"colorscheme kalt
"colorscheme kate
"colorscheme kellys
"colorscheme khaki
"colorscheme kib_darktango
"colorscheme kib_plastic
"colorscheme kings-away
"colorscheme kiss
"colorscheme kkruby
"colorscheme koehler
"colorscheme kolor
"colorscheme kruby
"colorscheme kyle
"colorscheme laederon
"colorscheme lakers_away
"colorscheme landscape
"colorscheme lanox
"colorscheme lanzarotta
"colorscheme lapis256
"colorscheme last256
"colorscheme late_evening
"colorscheme lazarus
"colorscheme legiblelight
"colorscheme leglight2
"colorscheme leo
"colorscheme less
"colorscheme lettuce
"colorscheme leya
"colorscheme lightcolors
"colorscheme LightDefaultGrey
"colorscheme LightDefault
"colorscheme lightning
"colorscheme LightTan
"colorscheme Light
"colorscheme LightYellow
"colorscheme lilac
"colorscheme lilydjwg_dark
"colorscheme lilydjwg_green
"colorscheme lilypink
"colorscheme lingodirector
"colorscheme liquidcarbon
"colorscheme literal_tango
"colorscheme lizard256
"colorscheme lizard
"colorscheme lodestone
"colorscheme loogica
"colorscheme louver
"colorscheme lucid
"colorscheme lucius
"colorscheme luinnar
"colorscheme lumberjack
"colorscheme luna-term
"colorscheme luna
"colorscheme lxvc
"colorscheme lyla
"colorscheme mac_classic
"colorscheme macvim-light
"colorscheme made_of_code
"colorscheme madeofcode
"colorscheme magellan
"colorscheme magicwb
"colorscheme mango
"colorscheme manuscript
"colorscheme manxome
"colorscheme marklar
"colorscheme maroloccio2
"colorscheme maroloccio3
"colorscheme maroloccio
"colorscheme mars
"colorscheme martin_krischik
"colorscheme materialbox
"colorscheme material-theme
"colorscheme materialtheme
"colorscheme material
"colorscheme matrix
"colorscheme maui
"colorscheme mayansmoke
"colorscheme mdark
"colorscheme mellow
"colorscheme messy
"colorscheme meta5
"colorscheme metacosm
"colorscheme midnight
"colorscheme miko
"colorscheme minimalist
"colorscheme minimal
"colorscheme mint
"colorscheme mizore
"colorscheme mod8
"colorscheme mod_tcsoft
"colorscheme mohammad
"colorscheme mojave
"colorscheme molokai_dark
"colorscheme molokai
"colorscheme monoacc
"colorscheme monochrome
"colorscheme monokai-chris
"colorscheme monokain
"colorscheme monokai-phoenix
"colorscheme Monokai
"colorscheme montz
"colorscheme moody
"colorscheme moonshine_lowcontrast
"colorscheme moonshine_minimal
"colorscheme moonshine
"colorscheme mophiaDark
"colorscheme mophiaSmoke
"colorscheme mopkai
"colorscheme more
"colorscheme moriarty
"colorscheme moria
"colorscheme morning
"colorscheme moss
"colorscheme motus
"colorscheme MountainDew
"colorscheme mourning
"colorscheme mrkn256
"colorscheme mrpink
"colorscheme mud
"colorscheme muon
"colorscheme murphy
"colorscheme mushroom
"colorscheme mustang
"colorscheme mythos
"colorscheme native
"colorscheme nature
"colorscheme navajo-night
"colorscheme navajo
"colorscheme nazca
"colorscheme nedit2
"colorscheme nedit
"colorscheme nefertiti
"colorscheme neodark
"colorscheme neon
"colorscheme neonwave
"colorscheme nerv-ous
"colorscheme nes
"colorscheme nets-away
"colorscheme neuromancer
"colorscheme neutron
"colorscheme neverland2-darker
"colorscheme neverland2
"colorscheme neverland-darker
"colorscheme neverland
"colorscheme neverness
"colorscheme nevfn
"colorscheme new-railscasts
"colorscheme newspaper
"colorscheme newsprint
"colorscheme nicotine
"colorscheme nightflight2
"colorscheme nightflight
"colorscheme nightshade_print
"colorscheme nightshade
"colorscheme nightshimmer
"colorscheme nightsky
"colorscheme night
"colorscheme night_vision
"colorscheme nightVision
"colorscheme nightwish
"colorscheme noclown
"colorscheme nocturne
"colorscheme nofrils-acme
"colorscheme nofrils-dark
"colorscheme nofrils-light
"colorscheme nofrils-sepia
"colorscheme no_quarter
"colorscheme nordisk
"colorscheme nord
"colorscheme northland
"colorscheme northpole
"colorscheme northsky
"colorscheme norwaytoday
"colorscheme nour
"colorscheme nuvola
"colorscheme obsidian2
"colorscheme obsidian
"colorscheme oceanblack256
"colorscheme oceanblack
"colorscheme oceandeep
"colorscheme OceanicNextLight
"colorscheme OceanicNext
"colorscheme oceanlight
"colorscheme off
"colorscheme olive
"colorscheme onedark
"colorscheme orange
"colorscheme osx_like
"colorscheme otaku
"colorscheme oxeded
"colorscheme pablo
"colorscheme pacific
"colorscheme paintbox
"colorscheme PapayaWhip
"colorscheme PaperColor
"colorscheme paramount
"colorscheme parsec
"colorscheme peachpuff
"colorscheme peaksea
"colorscheme pencil
"colorscheme penultimate
"colorscheme peppers
"colorscheme PerfectDark
"colorscheme perfect
"colorscheme petrel
"colorscheme pf_earth
"colorscheme phd
"colorscheme phoenix
"colorscheme phphaxor
"colorscheme phpx
"colorscheme pink
"colorscheme pixelmuerto
"colorscheme plasticine
"colorscheme playroom
"colorscheme pleasant
"colorscheme potts
"colorscheme predawn
"colorscheme preto
"colorscheme pride
"colorscheme primaries
"colorscheme primary
"colorscheme print_bw
"colorscheme prmths
"colorscheme professional
"colorscheme proton
"colorscheme ps_color
"colorscheme pspad
"colorscheme pt_black
"colorscheme putty
"colorscheme pw
"colorscheme py-darcula
"colorscheme pyte
"colorscheme python
"colorscheme quagmire
"colorscheme quantum
"colorscheme radicalgoodspeed
"colorscheme raggi
"colorscheme railscasts
"colorscheme rainbow_autumn
"colorscheme rainbow_fine_blue
"colorscheme rainbow_fruit
"colorscheme rainbow_night
"colorscheme rainbow_sea
"colorscheme rakr-light
"colorscheme random
"colorscheme rastafari
"colorscheme rcg_gui
"colorscheme rcg_term
"colorscheme rdark-terminal
"colorscheme rdark
"colorscheme redblack
"colorscheme redstring
"colorscheme Red
"colorscheme refactor
"colorscheme relaxedgreen
"colorscheme reliable
"colorscheme reloaded
"colorscheme revolutions
"colorscheme Revolution
"colorscheme robinhood
"colorscheme rockets-away
"colorscheme ron
"colorscheme rootwater
"colorscheme sadek1
"colorscheme sand
"colorscheme sandydune
"colorscheme satori
"colorscheme saturn
"colorscheme scheakur
"colorscheme scite
"colorscheme scooby
"colorscheme seagull
"colorscheme sean
"colorscheme seashell
"colorscheme seattle
"colorscheme selenitic
"colorscheme seoul256-light
"colorscheme seoul256
"colorscheme seoul
"colorscheme SerialExperimentsLain
"colorscheme seti
"colorscheme settlemyer
"colorscheme sexy-railscasts
"colorscheme sf
"colorscheme shadesofamber
"colorscheme shades-of-teal
"colorscheme shine
"colorscheme shiny-white
"colorscheme shobogenzo
"colorscheme sialoquent
"colorscheme sienna
"colorscheme sierra
"colorscheme sift
"colorscheme silent
"colorscheme simple256
"colorscheme simpleandfriendly
"colorscheme simple_b
"colorscheme simple_dark
"colorscheme simplewhite
"colorscheme simplon
"colorscheme skittles_autumn
"colorscheme skittles_berry
"colorscheme skittles_dark
"colorscheme sky
"colorscheme slate2
"colorscheme SlateDark
"colorscheme Slate
"colorscheme smarties
"colorscheme smpl
"colorscheme smp
"colorscheme smyck
"colorscheme soda
"colorscheme softbluev2
"colorscheme softblue
"colorscheme softlight
"colorscheme solarized8_dark_flat
"colorscheme solarized8_dark_high
"colorscheme solarized8_dark_low
"colorscheme solarized8_dark
"colorscheme solarized8_light_flat
"colorscheme solarized8_light_high
"colorscheme solarized8_light_low
"colorscheme solarized8_light
"colorscheme solarized
"colorscheme sole
"colorscheme sol-term
"colorscheme sol
"colorscheme sonofobsidian
"colorscheme sonoma
"colorscheme sorcerer
"colorscheme soruby
"colorscheme soso
"colorscheme sourcerer
"colorscheme southernlights
"colorscheme southwest-fog
"colorscheme spacegray
"colorscheme spacemacs-theme
"colorscheme space-vim-dark
"colorscheme spartan
"colorscheme spectro
"colorscheme spiderhawk
"colorscheme Spink
"colorscheme spring-night
"colorscheme spring
"colorscheme sprinkles
"colorscheme spurs_away
"colorscheme srcery-drk
"colorscheme srcery
"colorscheme stackoverflow
"colorscheme stefan
"colorscheme stereokai
"colorscheme stingray
"colorscheme stonewashed-256
"colorscheme stonewashed-dark-256
"colorscheme stonewashed-dark-gui
"colorscheme stonewashed-gui
"colorscheme stormpetrel
"colorscheme strange
"colorscheme strawimodo
"colorscheme summerfruit256
"colorscheme summerfruit
"colorscheme sunburst
"colorscheme surveyor
"colorscheme swamplight
"colorscheme sweater
"colorscheme SweetCandy
"colorscheme symfony
"colorscheme synic
"colorscheme synthwave
"colorscheme tabula
"colorscheme tango2
"colorscheme tango-desert
"colorscheme tango-morning
"colorscheme tangoshady
"colorscheme tango
"colorscheme tangoX
"colorscheme taqua
"colorscheme tatami
"colorscheme tayra
"colorscheme tchaba2
"colorscheme tchaba
"colorscheme tcsoft
"colorscheme telstar
"colorscheme tender
"colorscheme termschool
"colorscheme tesla
"colorscheme tetragrammaton
"colorscheme textmate16
"colorscheme thegoodluck
"colorscheme thermopylae
"colorscheme thestars
"colorscheme thornbird
"colorscheme thor
"colorscheme tibet
"colorscheme tidy
"colorscheme tigrana-256-dark
"colorscheme tigrana-256-light
"colorscheme tir_black
"colorscheme tolerable
"colorscheme tomatosoup
"colorscheme Tomorrow-Night-Blue
"colorscheme Tomorrow-Night-Bright
"colorscheme Tomorrow-Night-Eighties
"colorscheme Tomorrow-Night
"colorscheme Tomorrow
"colorscheme tony_light
"colorscheme toothpik
"colorscheme torte
"colorscheme transparent
"colorscheme triplejelly
"colorscheme trivial256

"colorscheme trogdor
"colorscheme tropikos
"colorscheme true-monochrome
"colorscheme turbo
"colorscheme turtles
"colorscheme tutticolori
"colorscheme twilight256
"colorscheme twilight
"colorscheme twitchy
"colorscheme two2tango
"colorscheme two-firewatch
"colorscheme ubaryd
"colorscheme ubloh
"colorscheme umber-green
"colorscheme understated
"colorscheme underwater-mod
"colorscheme underwater
"colorscheme up
"colorscheme vanzan_color
"colorscheme vcbc
"colorscheme vc
"colorscheme vertLaiton
"colorscheme vexorian
"colorscheme vibrantink
"colorscheme vice
"colorscheme vilight
"colorscheme vimicks
"colorscheme vim-material
"colorscheme visualstudio
"colorscheme vividchalk
"colorscheme VIvid
"colorscheme vj
"colorscheme void
"colorscheme vydark
"colorscheme vylight
"colorscheme wargrey
"colorscheme warm_grey
"colorscheme warriors-away
"colorscheme watermark
"colorscheme welpe
"colorscheme White2
"colorscheme whitebox
"colorscheme whitedust
"colorscheme white
"colorscheme widower
"colorscheme wikipedia
"colorscheme win9xblueback
"colorscheme winterd
"colorscheme wintersday
"colorscheme winter
"colorscheme wolfpack
"colorscheme wombat256dave
"colorscheme wombat256i
"colorscheme wombat256mod
"colorscheme wombat256
"colorscheme wombat
"colorscheme wuye
"colorscheme wwdc16
"colorscheme wwdc17
"colorscheme xcode-default
"colorscheme xcode
"colorscheme xedit
"colorscheme xian
"colorscheme xmaslights
"colorscheme xoria256
"colorscheme yeller
"colorscheme zazen
"colorscheme zellner
"colorscheme zenburn
"colorscheme zenesque
"colorscheme zen
"colorscheme zephyr
"colorscheme zmrok
